spring:
  liquibase:
    change-log: classpath:db/changelog.xml
    contexts: dev

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/transaction_db
    username: postgres
    password: postgres

  artemis:
    mode: embedded

server:
  error:
    include-message: always
